curl https://randomuser.me/api/portraits/lego/9.jpg > Odelia_Canas.jpg
curl https://randomuser.me/api/portraits/lego/7.jpg > Giovanni_Lipford.jpg
curl https://randomuser.me/api/portraits/lego/0.jpg > Mickey_Dart.jpg
curl https://randomuser.me/api/portraits/lego/0.jpg > Miyoko_Marsden.jpg
curl https://randomuser.me/api/portraits/lego/1.jpg > Marcella_Palencia.jpg
curl https://randomuser.me/api/portraits/lego/3.jpg > Zane_Lafontaine.jpg
curl https://randomuser.me/api/portraits/lego/9.jpg > Laurel_Coyer.jpg
curl https://randomuser.me/api/portraits/lego/9.jpg > Lloyd_Yelverton.jpg
curl https://randomuser.me/api/portraits/lego/2.jpg > Sterling_Digman.jpg
curl https://randomuser.me/api/portraits/lego/7.jpg > Mable_Lowenstein.jpg
